stages:
  - test

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"

matrix:
  allow_failures:
    - python: "nightly"
  include:
    - name: python 3.6 default
      language: python
      python: 3.6
      install: pip install .
      script:
        - ./test/py_test.sh

